### PR TITLE
Interactivity examples

### PR DESCRIPTION
**Pull request by makella**
@Jesus89 

I did some adjusting to the examples for interactivity.

I still need to do the `feature-enter-leave` either by adjusting the symbology for what you have or finding another dataset.

I'll do that tomorrow!

thanks,
mamata

### CODE REVIEW

**Comment by Jesus89** [comment]
Hi @makella. OK!

NOTE: I see that you are using the `flat-corners` branch instead of `master` branch. I'll try to work on this branch `interact-examples` to fix that. Maybe you will need to reset your local branch with the updated one.

**Comment by Jesus89** [comment]
Hi! I have fixed the issue with the other branch. I have `cherry-picked` your commits and updated your branch with that :)

First of all you need to update your local branch with this new fixed branch:

1. Move to the `interact-examples` branch

```
git checkout interact-examples
```

2. Update the fixed branch

```
git reset --hard origin/interact-examples
```

And thats all!

Then you can continue adding commits and improvements ;)

**Comment by makella** [comment]
oh my gosh @Jesus89!! sorry! I don't know what happened I was pushing to my `interact-examples` anyway, it was late! sorry again!

**Comment by makella** [comment]
@Jesus89 Ok!

Did some more work on the feature style example plus one or two other minor adjustments.

I'm still not super happy with the rivers in the `feature enter/exit`... trying to find another line dataset that is more discrete like that one. In the mean time, I did a small adjustment to the line widths.

**Comment by Jesus89** [comment]
Perfect @makella!

I did also minor (minor) fixes in some examples. The `Style feature` example has some bugs (related to the implementation of the functionality) so we will wait until this is fixed and also the `enter/leave` example for the merge.

**Comment by makella** [comment]
ok! so we will merge these all at once?

**Comment by Jesus89** [comment]
If you want, we can merge it now and then open more PRs in the future if required.

**Comment by makella** [comment]
you decide! the only reason I think it would be good is so others see the examples and if there are any comments on the refreshed ones, we can incorporate.

**Pull request merged**
